version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_SCHEMA}
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: springtest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9191:9191"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: